### ISSUE TITLE
Darken background

### ISSUE THREAD

**Issue by trevordmiller** [trevordmiller/nova-colors#16]
A number of people have requested the background color be darkened; although I want to keep the theme more towards the subtle / pastel / lower contrast, I also want it to be readable

- Update the `novaColors.normal.black`
- Pull latest `nova-colors` in all plugins for all `nova-*` repos
- Update screenshots for all `nova-*` repos

![screen shot 2016-09-22 at 4 17 26 pm](https://cloud.githubusercontent.com/assets/5497885/18768125/5bf4b998-80e0-11e6-9e4f-b2c23d2f7ec3.png)
![screen shot 2016-09-22 at 4 17 14 pm](https://cloud.githubusercontent.com/assets/5497885/18768123/5bf36e4e-80e0-11e6-8679-2cdda781fb6b.png)
![screen shot 2016-09-22 at 4 16 22 pm](https://cloud.githubusercontent.com/assets/5497885/18768127/5bf62a80-80e0-11e6-8dd3-20d6fe24a2dd.png)
![screen shot 2016-09-22 at 4 16 02 pm](https://cloud.githubusercontent.com/assets/5497885/18768124/5bf47a96-80e0-11e6-8540-aa8c6e70d0f4.png)
![screen shot 2016-09-22 at 4 15 56 pm](https://cloud.githubusercontent.com/assets/5497885/18768126/5bf62b52-80e0-11e6-81f8-3ff3261b0476.png)

**Comment by ffxsam** [comment]
What I like about Solarized Dark is that it has a decent amount of contrast without being too stark (e.g. white on black). I also don't like coding on light backgrounds, since white emitted from LED screens = blue light, to which long-term exposure might have negative effects on the eyes.

**Comment by trevordmiller** [comment]
Nova `normal.black` (base background) is now 20% darker.
https://github.com/trevordmiller/nova-colors/pull/17

# Vim

https://github.com/trevordmiller/nova-vim/pull/18

#### Before

<img width="1440" alt="vim-before" src="https://cloud.githubusercontent.com/assets/5497885/18774355/664828dc-8115-11e6-85cf-da463f0bc114.png">

#### After

<img width="1440" alt="vim-after" src="https://cloud.githubusercontent.com/assets/5497885/18774358/6a557934-8115-11e6-8940-27f8b48f8331.png">

# Atom

https://github.com/trevordmiller/nova-atom-syntax/pull/11
https://github.com/trevordmiller/nova-atom-ui/pull/12

#### Before

<img width="1440" alt="atom-before" src="https://cloud.githubusercontent.com/assets/5497885/18774461/b0fbecbe-8116-11e6-8be1-a8de4c922704.png">

#### After

<img width="1440" alt="atom-after" src="https://cloud.githubusercontent.com/assets/5497885/18774464/bb23f5c4-8116-11e6-9aa6-88b2b917bb66.png">

# HyperTerm

https://github.com/trevordmiller/nova-hyperterm/pull/8

#### Before

<img width="960" alt="hyperterm-before" src="https://cloud.githubusercontent.com/assets/5497885/18774010/f9ce9360-8111-11e6-819b-5c7caee5de9b.png">

#### After

<img width="960" alt="hyperterm-after" src="https://cloud.githubusercontent.com/assets/5497885/18774012/fe4a8c1e-8111-11e6-9179-042348ab5a48.png">

#### Manual upgrade required (HyperTerm doesn't have auto-updates yet)

<img width="445" alt="hyperterm-upgrade" src="https://cloud.githubusercontent.com/assets/5497885/18774025/17a32914-8112-11e6-9e03-bcd34de9f37c.png">

# iTerm

https://github.com/trevordmiller/nova-iterm/pull/10

#### Before

<img width="960" alt="iterm-before" src="https://cloud.githubusercontent.com/assets/5497885/18774191/e36c1906-8113-11e6-97f9-20b2b4f417c5.png">

#### After

<img width="960" alt="iterm-after" src="https://cloud.githubusercontent.com/assets/5497885/18774192/e7839e06-8113-11e6-9c96-3afb8ebbf5ad.png">

# Docs

https://github.com/trevordmiller/nova/pull/29

#### Before

<img width="1004" alt="docs-before" src="https://cloud.githubusercontent.com/assets/5497885/18774638/780c73c2-8118-11e6-8043-5a44b0934da5.png">

#### After

<img width="872" alt="docs-after" src="https://cloud.githubusercontent.com/assets/5497885/18774639/7c98544c-8118-11e6-95a3-020a0ad2a452.png">

cc: @iammerrick
