### ISSUE TITLE
Add VSCode plugin

### ISSUE THREAD

**Issue by trevordmiller** [trevordmiller/nova-colors#18]
In development by @rebornix [on VS marketplace](https://marketplace.visualstudio.com/items?itemName=rebornix.nova)

**Comment by trevordmiller** [comment]
@rebornix

First, thank you for taking this on! I appreciate it and am looking forward to adding the VSCode plugin to the website.

Here is some feedback on your first draft:
1) See the screenshots on https://trevordmiller.github.io/nova. The Atom plugin is probably the closest to VSCode that you can use as an example; can you match 
2) Only use `nova-colors` values - right now there are many non-nova-colors values so it doesn't look consistent with the rest of Nova for both syntax and UI (tree view, tabs, file names, file icons etc)
3) Use the color meanings as explained on the top of https://trevordmiller.github.io/nova; for example, in your version, globals are `novaColors.normal.yellow` when they should be `novaColors.normal.magenta`. Please see the [`nova-vim`](https://github.com/trevordmiller/nova-vim/blob/master/src/index.js), [`nova-atom-syntax`](https://github.com/trevordmiller/nova-atom-syntax/tree/master/styles), and [`nova-atom-ui`](https://github.com/trevordmiller/nova-atom-ui/blob/master/index.less) plugins to see how color meanings are styles based on syntax / UI group.

I look forward to reviewing your next iteration! Once it is ready, you can use the `nova-colors` values directly and then we can add it to the Nova website.

**Comment by trevordmiller** [comment]
cc: @iammerrick

**Comment by rebornix** [comment]
@trevordmiller thanks for the tip! I'm already using `nova-colors` and npm scripts to replace the manual work. I'll update the colors per documentation as well. Here are two things I'm not quite clear with 

> 1)Fork one of the existing repos
> 5)Submit a pull request to the "nova" repo "platforms"

Currently I created a new repo called `vscode-nova` instead of forking and renaming, but I'll redo 1) if you think forking is a good start. About 5), I don't see any repo named as `platforms`, any ideas?

**Comment by rebornix** [comment]
Another catch is Code plugin requires a logo, which seems missing in all other plugins right now, I'd like to use the favicon but that's too small somehow:)

**Comment by trevordmiller** [comment]
@rebornix Thanks for the feedback. I think I'll update those instructions to be clearer. #1 is fine if you didn't do it, just a suggestion so you see how a Nova plugin works. #5 is referring to adding it to the [`nova`](https://github.com/trevordmiller/nova) documentation website repo [`platforms`](https://github.com/trevordmiller/nova/blob/master/src/data/platforms.js) which I will help you with once the plugin is ready. As for the logo, I have a few different versions; what do you need? Square? What size(s) will it be displayed at? I can get you the logo once I know where it is being used.

**Comment by rebornix** [comment]
A 128*128 square logo will be good. It's used as the identifier of an extension on both the marketplace and the extension viewlet in VS Code. You can take a look at https://marketplace.visualstudio.com/items?itemName=vscodevim.vim to gather an idea.

For the rest of feedback, I'll update later and let you know if I have problems, thanks!

**Comment by trevordmiller** [comment]
@rebornix Oh ok cool. Here is a logo (full + 128 sizes) for you to use; let me know if you need a different version. As for the background color, either the `normal.black`, `normal.cyan` or `normal.white`, whatever looks better. Thank you.

### Full

![nova-icon-full](https://cloud.githubusercontent.com/assets/5497885/18795841/a7dad0c4-8183-11e6-8814-1ded42a31d8d.png)

### 128

![icon-128](https://cloud.githubusercontent.com/assets/5497885/18795955/515d90aa-8184-11e6-929a-e5394d853963.png)

**Comment by rebornix** [comment]
Cool, the logo looks amazing.

BTW, while mapping the color palate to Code tokens, I tried to follow `nova-atom`'s behavior and ran into below two issues: 

1. I can't make my Atom to display the same color as the website demos. The `import` is yellow while on the website, it shows as `magenta`. Do I need to install any specific plugin which helps tokenizing JavaScript/ES6 files ?
![screen shot 2016-09-23 at 10 54 12 am](https://cloud.githubusercontent.com/assets/876920/18796060/6b9a821e-817c-11e6-8479-e33f76693a3f.png)
2. VS Code follows the way how TextMate does theming. So basically we are using the same tokenization engine as TextMate, so does Sublime. As you can see in my repo, I'm generating a `tmTheme` file. Once that's optimized perfectly, it can be shared between TextMate, Sublime or maybe Jetbrains IDEs. The only catch is, currently Nova-Atom is grouping tokens in its own way, which doesn't match with Code/TextMate/Sublime. I'll try to make the `tmTheme` reasonable, but if there is anything wrong, let me know and then fix it.

**Comment by trevordmiller** [comment]
@rebornix Good point. I don't use Atom, but I do have installed the `language-babel` for ES6+
![image](https://cloud.githubusercontent.com/assets/5497885/18796448/8a17b8ce-8186-11e6-9bc6-826f11bf1832.png)

I would say, try your best to follow the color meanings but I realize not every editor has every syntax group so if you need to substitue another Nova color value that's ok :)
![image](https://cloud.githubusercontent.com/assets/5497885/18796474/a4c34d28-8186-11e6-81cd-858b00c9f5e4.png)

That's cool that the tokens can be shared across Code/Sublime/TextMate - I didn't know that. I bet @carsonjones will be interested in re-using your work in https://github.com/trevordmiller/nova-colors/issues/19.

**Comment by iammerrick** [comment]
Hey @rebornix @carsonjones if you can show me how to find the token groups that textmate/sublime uses for ES6 I can add support for the meanings like we have in VIM.

**Comment by iammerrick** [comment]
Also, authoring as tmTheme for Sublime support is epic! (Not to mention nostalgic I miss textmate)

**Comment by rebornix** [comment]
@iammerrick Textmate's basic token group is documented here https://manual.macromates.com/en/language_grammars . It doesn't have any specific grammar for ES6, but the engine allows to define your own tokenize logic.

So in VS Code, we have builtin JavaScript (with React) tokenization support, see [here](https://github.com/Microsoft/vscode/blob/master/extensions/javascript/syntaxes/JavaScript.tmLanguage.json).  So what we need to do is assigning colors to all the scopes listed in that file then you can see it in VS Code.

I'm not quite sure what's the default JavaScript language grammar in Sublime as it's not open sourced. However, you can always write a plugin with the grammar ( called `tmLanguage` ) Code uses and the `tmTheme` I wrote for Code. Then Sublime will behave the same way as Code.

**Comment by igetgames** [comment]
@rebornix I wasn't trying to duplicate your efforts, but I ended up starting an attempt at a Nova theme for VS Code (here)[https://github.com/igetgames/nova-vscode]. There doesn't appear to be any feedback on Microsoft/vscode#3112, so I plan to take the approach of injecting CSS in an effort of adding my own "uiTheme". This approach requires the theme to be a full extension with support for activation. However injecting code in this way is not supported by the Code team AFAICT.

Following this discussion, it appears that the same tmTheme could be used for multiple editors. Would it make sense to split the template generation of Nova.tmTheme into a separate package?

**Comment by rebornix** [comment]
@igetgames I see your progress and it's really an awesome idea. We didn't have that kind of support yet and `injecting code` is not a good thing to do. 

`tmTheme` works in Sublime and TextMate as well so yeah I'll move that part to a separate package for better integration.

**Comment by rebornix** [comment]
@igetgames here it is https://github.com/rebornix/nova-tmtheme

**Comment by igetgames** [comment]
Great! I will incorporate this. I think that your theme should be included in the Nova docs as the main VS Code Nova theme. I will tinker with mine, but I'm going to be venturing into unsupported areas that will possibly be obsoleted or locked down at some point. If I do succeed then I would like see my implementation included as an alternative.

Hopefully the VS Code team will respond regarding that issue and let the community know whether or not we can theme the VS Code chrome.

**Comment by trevordmiller** [comment]
Thanks @rebornix!

**Comment by Tyriar** [comment]
@igetgames the workbench theme support is on our road map, and planned for this release was to show a notification to the user when vscode has had code injected and is therefore unsupported. 

I would avoid doing this and just wait it out for the relevant APIs if I were you, we've had a significant number of "critical"  issues that have come in due to these extensions changing the source code of vscode. The team wasted quite a lot of time looking into these issues last release that could have been spend doing something more productive.

**Comment by igetgames** [comment]
Thanks Daniel, point taken. I'll wait for the official support.

**Comment by carsonjones** [comment]
Thanks for knocking that out @rebornix , going to be a big help for getting the sublime version ([#19](https://github.com/trevordmiller/nova-colors/issues/19)) done.

**Comment by trevordmiller** [comment]
Yes, thank you @rebornix! I appreciate that you used the `nova-vim` colors with a build step and split up the syntax groups to match the color meanings like we did with the Vim and Atom plugins. 👍

**Comment by trevordmiller** [comment]
@rebornix fyi, I just released `nova-colors` `2.0.0` with a cleaner API for Nova color mappings to meanings, depending on the context; it's still the same color values, but the mappings should be more clear and easier to use for different contexts hopefully: https://github.com/trevordmiller/nova-colors/pull/24/files. If you are still willing to build the Sublime theme, please update your `tmTheme` for the sublime plugin with this new API and we should be good to merge + add to the website and share :) Let me know when you are ready. Thank you again for your work!
Also, fyi @ijones16 mentioned he is interested in helping if you'd like

**Comment by trevordmiller** [comment]
@rebornix 

Here's how I updated the Vim and HypterTerm plugins to use the [`nova-colors` 2 API](https://github.com/trevordmiller/nova-colors/blob/master/src/index.js)
- https://github.com/trevordmiller/nova-vim/pull/29/files
- https://github.com/trevordmiller/nova-hyperterm/pull/12/files

**Comment by trevordmiller** [comment]
Hey @rebornix  did my last two comments make sense? ^

**Comment by rebornix** [comment]
@trevordmiller I'm back to China for wedding. I'll align my code with new API late this week :)

**Comment by trevordmiller** [comment]
@rebornix Awesome! Let me know when you are done and I'll help you add it to the website. Thanks!

**Comment by carsonjones** [comment]
I recently have been trying VSCode and needed Nova in more than my editor window, so even though it isn't supported yet, I took a stab at restyling my work bench. Sorry @Tyriar !

To make it work, install the [`vscode-custom-css`](https://github.com/be5invis/vscode-custom-css) plugin. Then add this snippet to your settings.json:

`json
"vscode_custom_css.imports": [
  "https://carsonjones.github.io/vscode-config/css/style.css"
],
`

After than, run cmd+shift+p and "Enable Custom CSS and JS. Restart your editor and you're good to go.

When combined with the Nova Colors TmTheme - you get pretty close!

@trevordmiller I wanted to share this so anyone can take it and run with it! My colors might not match exactly and probably needs some work.

Credit to @dominique-mueller for his custom styling gist [`here`](https://gist.github.com/dominique-mueller/0d9f5aec202804caca4881838685cfc4)

**Comment by trevordmiller** [comment]
@rebornix What do you think about this ^? Are you still working on the Nova VSCode theme? I'd like to either close this issue or get a PR merged in sometime soon :)

**Comment by rebornix** [comment]
@trevordmiller sorry for postponing this for so long. You may know I just move to Seattle and got too many things to settle down so I'm not quite sure about if I can get accurate timing for this theme on Code but will do. Feel free to close this first :)

**Comment by trevordmiller** [comment]
Ok I'm going to close this for now. If anyone wants to take this on, let me know and I'll reopen :)

**Comment by trevordmiller** [comment]
An update for those interested in a VSCode plugin for Nova:

Since this issue was closed, I've had many ask if Nova can get an official VSCode plugin. My answer is - absolutely! ...if someone else will build and maintain it 😜

The themes that currently exist for VSCode are not official: they haven't implemented [the `nova-colors` package](https://github.com/trevordmiller/nova-colors) fully as [the official plugins do](https://trevordmiller.com/projects/nova). I don't use VSCode myself so I don't want to take on maintaining it personally, sorry. But, if someone creates a VSCode plugin that uses `nova-colors` fully I'll happily add it to the website 🎉

If you are interested in contributing, you may be able to use some of the work done previously in this issue ☝️, but it might be easier to just fork the [nova-vim](https://github.com/trevordmiller/nova-vim) plugin. Here is a blog post explaining how official plugins were built that can guide you: https://trevordmiller.com/blog/color-scheme-building. The critical piece being each official Nova plugin has a build step that maps the `nova-colors` npm package by color meaning to UI groups and syntax for modern web development languages.

If anyone wants to take a whack at an official version let me know :)

cc: @splodingsocks @geddski @spicydonuts

**Comment by rebornix** [comment]
As I published the Nova extension to VSCode marketplace, I still feel that I should make updates to it, especially make it appeal to VSCode's workspace theme settings. I don't have a way to auto generate everything so I'm doing it manually, but it still works. Here is my current status

## Workbench
#### Atom

![image](https://user-images.githubusercontent.com/876920/30530563-7dac8a24-9bfc-11e7-84da-034c99044490.png)

#### VSCode

![image](https://user-images.githubusercontent.com/876920/30530588-bae13840-9bfc-11e7-9836-c4a8b9ff1d00.png)


## TODO
- [ ] Diff
- [ ] Merge
- [ ] Dropdown
- [ ] Hover
- [ ] Panel
- [ ] Debug
- [ ] Peek

**Comment by trevordmiller** [comment]
@rebornix Wonderful!

> "I don't have a way to auto generate everything so I'm doing it manually"

How come you can't use the `nova-colors` package with a build step like the other official plugins do? For example: https://github.com/trevordmiller/nova-vim.

Once you are using the `nova-colors` mapped correctly to color meanings I'll happily add it to the website and share it as an official plugin - let me know! Thank you for your help 👏

**Comment by trevordmiller** [comment]
Also @rebornix, the Atom plugin is a little bit behind, I'd recommend using the Vim plugin as your example (specifically the tab styles have much better contrast now):

![image](https://user-images.githubusercontent.com/5497885/30549212-74b44e7a-9c51-11e7-8010-a9ad524b2b89.png)

![image](https://user-images.githubusercontent.com/5497885/30549267-8fa8fb54-9c51-11e7-94fd-d1db0046e5af.png)

**Comment by rebornix** [comment]
@trevordmiller yes I'm using nova-colors to keep update with your predefined colors. The problem I raised is I need to map those colors to UI elements one by one, it's not like TM Theme which has predefined scope. Anyways below is current status, it would be great if you can help review it.

#### Empty workbench
![image](https://user-images.githubusercontent.com/876920/30568296-2de82c68-9c89-11e7-9a77-9b621d26aa7c.png)

#### File Explorer
![image](https://user-images.githubusercontent.com/876920/30568327-6536f44c-9c89-11e7-80f0-e13606be8dd9.png)

#### Suggest Window
![image](https://user-images.githubusercontent.com/876920/30568381-b9f2b53e-9c89-11e7-81d8-f5623d7ca910.png)

#### Find All References 
![image](https://user-images.githubusercontent.com/876920/30568397-df8066d4-9c89-11e7-9392-652f193c5506.png)

#### Diff
![image](https://user-images.githubusercontent.com/876920/30568583-cca997e6-9c8a-11e7-8d6a-88dab4b34aab.png)

#### Terminal

![image](https://user-images.githubusercontent.com/876920/30568620-05fcb604-9c8b-11e7-9a60-6159c2a72e50.png)

#### Quick Pick
![image](https://user-images.githubusercontent.com/876920/30568636-1389418e-9c8b-11e7-8a25-92f4eab5c537.png)

#### Extension View

![image](https://user-images.githubusercontent.com/876920/30568684-631596f8-9c8b-11e7-9a78-ea42b00130a8.png)

**Comment by trevordmiller** [comment]
@rebornix Great work! Thank you for your efforts, they are much appreciated :)

I'm reviewing the latest theme in VSCode and logging a few issues on your repo:
https://github.com/rebornix/vscode-nova/issues

Once those issues are taken care of, we can add your plugin to the Nova website officially and close this issue!

**Comment by trevordmiller** [comment]
@rebornix Any updates on this? I'd really like to get this finished up soon if possible :) Thanks for your work!

**Comment by rebornix** [comment]
@trevordmiller I'm taking paternal leave from last month so the response is late. Here is the current status of Nova for VSCode.

I already tweaked the theme per your issues but there are still some left https://github.com/rebornix/vscode-nova/issues?q=is%3Aissue+is%3Aopen+label%3Aupstream , however they are limited to current Code API. For short, these issues are

* https://github.com/rebornix/vscode-nova/issues/9 Customized theme for JSX in JavaScript
* https://github.com/rebornix/vscode-nova/issues/8, https://github.com/rebornix/vscode-nova/issues/6 Code recommends to use background for selection instead of changing text color. (however this is doable but requires workaround with decorations)
* https://github.com/rebornix/vscode-nova/issues/4 Color for current line number

Let me know if this is acceptable to you @trevordmiller

**Comment by trevordmiller** [comment]
@rebornix No worries, congrats on your new baby!

I just closed https://github.com/rebornix/vscode-nova/issues/8 and https://github.com/rebornix/vscode-nova/issues/6 to default to the code way of doing things. I left open https://github.com/rebornix/vscode-nova/issues/9 and https://github.com/rebornix/vscode-nova/issues/4 for you to improve when you have time in the future but they don't have to be done right now.

With those updates, I now feel comfortable adding your theme to the website and sharing it as the official Nova VSCode plugin! I should be able to do this tomorrow and will mention you when I share it. Thanks for all of your work :)

---

# Trevor's task list for initial vscode-nova release

- [ ] Add to https://trevordmiller.com/projects/nova plugins list
- [ ] Share across social media, reddit, previous posts that asked for VSCode, etc. (mention rebornix)
- [ ] Update recurring social media post (from MeetEdgar) to mention VSCode

**Comment by trevordmiller** [comment]
@rebornix Alright, your vscode-nova plugin has been officially released!

It has been added to [the Nova website](https://trevordmiller.com/projects/nova):

![image](https://user-images.githubusercontent.com/5497885/31400421-c4dbf4e0-adac-11e7-8fa3-becf363b6515.png)
Done in https://github.com/trevordmiller/trevordmiller-website/pull/124

I've shared it across the web:
- [Reddit](https://www.reddit.com/r/vscode/comments/75itcn/new_color_theme_for_vs_code/)
- [Twitter](https://twitter.com/trevordmiller/status/917807457417691136)
- [Facebook](https://www.facebook.com/trevordmillercom/photos/a.946233105518021.1073741828.944447972363201/997812063693458)
- [LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:6323573129738223616/)

My Nova item in my repeating social media sharing (via MeetEdgar) has been updated to mention it:
![image](https://user-images.githubusercontent.com/5497885/31400567-49c3d574-adad-11e7-91e3-01b0aab963b7.png)

Thanks again for your work!
