### ISSUE TITLE
Add Sublime plugin

### ISSUE THREAD

**Issue by trevordmiller** [trevordmiller/nova-colors#19]
In development by @carsonjones

**Comment by trevordmiller** [comment]
Hey @carsonjones and others, please see the work being done to build the VSCode plugin in this issue as it looks like much of it could be reused with the `tmTheme`:
https://github.com/trevordmiller/nova-colors/issues/18#issuecomment-249376494

cc: @rebornix @iammerrick

**Comment by rebornix** [comment]
Move `tmTheme` alone to a separate repo https://github.com/rebornix/nova-tmtheme

**Comment by trevordmiller** [comment]
Thanks @rebornix!

**Comment by carsonjones** [comment]
Quick update for everyone - thanks to @rebornix, my Sublime is starting to look like a champagne super-nova (get it) with a few modifications to the tmtheme file.

Tonight I plan on figuring out the best way to wrap the theme as a Sublime Plugin for easy install, and of course, get everything I've done merged in. Thanks for your patience!

Here's a preview for the curious:

<img width="637" alt="__dev_projects_nova_nova_src_components_app_js_ _nova" src="https://cloud.githubusercontent.com/assets/5290878/18839315/61365a60-83bf-11e6-8d2d-70911313fc94.png">

**Comment by rebornix** [comment]
@carsonjones quite awesome! Do you mind sending your change against https://github.com/rebornix/nova-tmtheme then Code can benefit from the change as well? Or I can do it myself once you have it merged.

**Comment by iammerrick** [comment]
Thank you @carsonjones @rebornix so exciting for me!

**Comment by trevordmiller** [comment]
@carsonjones Thanks so much for your work on this! Many people are looking forward to it and it will be a great help :) This is looking pretty good; it seems like not all syntax groups have been mapped to their color meanings (for example, `this` and import keywords should be `novaColors.normal.magenta` for "global", and class method names should be `novaColors.normal.blue` for "identifier" etc.); please review how the [Atom plugin](https://github.com/trevordmiller/nova-atom-syntax/blob/master/styles/languages.less#L13-L105) and [Vim plugin](https://github.com/trevordmiller/nova-vim/blob/master/colors/nova.vim#L75-L262) map Nova color values to their meanings across JS, HTML, CSS, Markdown, and JSX; if you and @rebornix could finish mapping all the common syntax groups for the `tmTheme` then I'll happily help you add both the VSCode and Sublime plugins to the Nova website :)

Thanks again for your work! Looking forward to it.

**Comment by LasseRafn** [comment]
+1

**Comment by trevordmiller** [comment]
@carsonjones fyi, I just released `nova-colors` `2.0.0` with a cleaner API for different color groups; it's still the same color values, but the mappings should be more clear and easier to use for different contexts hopefully: https://github.com/trevordmiller/nova-colors/pull/24/files. If you are still willing to build the Sublime theme, please update your `tmTheme` for the sublime plugin with this new API and we should be good to merge + add to the website and share :) Let me know when you are ready. Thank you again for your work!

**Comment by trevordmiller** [comment]
@carsonjones 
Here's how I updated the Vim and HypterTerm plugins to use the [`nova-colors` 2 API](https://github.com/trevordmiller/nova-colors/blob/master/src/index.js)
- https://github.com/trevordmiller/nova-vim/pull/29/files
- https://github.com/trevordmiller/nova-hyperterm/pull/12/files

**Comment by trevordmiller** [comment]
Hey @carsonjones did my last two comments make sense? ^

**Comment by TheShiftExchange** [comment]
@carsonjones - polite bump - is this something you are still working on?

**Comment by carsonjones** [comment]
Hi @theshiftexchange, I have not finished this project and do not see time to do so. Would you like to step in?

My progress to date has only included making a slight modification to the tmTheme file found in this repo: [https://github.com/rebornix/nova-tmtheme](https://github.com/rebornix/nova-tmtheme) .

Sublime has a hard time picking up es6 styles, which is where I got stuck. Maybe this is where you can help. (specifically the this and import keywords).

@trevordmiller recently adjusted the mappings, so hopefully this will help with the problem above.

Here is my tmTheme file: [gist link](https://gist.github.com/carsonjones/81f409e308a3ff83e0e65253084dcef9)

**Comment by kurtextrem** [comment]
https://packagecontrol.io/packages/JavaScriptNext%20-%20ES6%20Syntax is a packagefor ES6 syntax, but I'm quite sure that package has been merged into Sublime's default already.

**Comment by trevordmiller** [comment]
There is a pull request in by @driesvints for a sublime plugin; looks pretty solid! Just needs a few tweaks and then I think we can merge it in and iterate from there:
https://github.com/trevordmiller/nova/pull/77#pullrequestreview-6537434

**Comment by driesvints** [comment]
Oh crap, I totally missed this, so sorry! 

@carsonjones would you mind if I ported your `src` file to my repo? I'll add you as a copyright holder and link to your Github in the readme. I can even add you as a maintainer if you want.

**Comment by driesvints** [comment]
I can add more people as maintainer for that matter. @trevordmiller if you also want access, let me know.

**Comment by trevordmiller** [comment]
@driesvints It's ok it was hidden :) Your `src` is actually more up-to-date (it's using latest `nova-colors`) so I'd prefer we still with what you've built :) No offense to @carsonjones, I know he made some good progress but didn't have as much time to finish it. I just wanted to post that here so those that were following this issue could see your progress. I am not planning on maintaining any other plugins officially as I have my hands full with the Vim, Atom, Hyper, and iTerm ones, but I welcome these additions! If you will address those three things I mentioned in your pull request, we can get this merged in.

**Comment by trevordmiller** [comment]
I'm closing this for now, since it is lower priority than other things I'm working on. I know some attempts have been made to create a sublime plugin; I appreciate it! However, none of these have been complete or used the `nova-colors` package as the other official plugins do and I don't plan to support this myself. If anyone would like to re-open the issue and submit a pull request, let me know! I'd be happy to have your contribution :)
