### ISSUE TITLE
Add non-default exports for color meanings

### ISSUE THREAD

**Issue by Tyriar** [trevordmiller/nova-colors#20]
If the colors in https://github.com/trevordmiller/nova-colors/blob/master/index.js were named using their semantic meanings you could then potentially create generalized tool(s) that generate themes for a wide variety of editors in a general way. To then generate a new theme all you would need to do is create a new package, change the colors and run the generation tools.

**Comment by trevordmiller** [comment]
@Tyriar Thank you for your feedback. I thought about using the semantic naming for the object keys, but decided against it for two reasons: 1) some colors are used for more than one purpose (ex. `normal.cyan` is for both constants + user state), and 2) not all implementations have semantic meaning (ex. the terminal color overrides need to map to the ANSI equivalents as you can see in [the HyperTerm plugin](https://github.com/trevordmiller/nova-hyperterm/blob/master/index.js#L11-L26) and [the Neovim section of the Vim plugin](https://github.com/trevordmiller/nova-vim/blob/master/src/index.js#L58-L73)); so, I used the ANSI groups and rely on plugins to map them to the meanings if they apply (as you can see in [the Vim plugin] (https://github.com/trevordmiller/nova-vim/blob/master/src/index.js#L107) and [the Atom plugin](https://github.com/trevordmiller/nova-atom-syntax/blob/master/styles/colors.less#L27-L40)). If you have a better way to do this, feel free to submit a PR as I'm open to suggestions :)

**Comment by bugpowder** [comment]
> If you have a better way to do this, feel free to submit a PR as I'm open to suggestions :)

Perhaps have the basic names as the default export from the npm, and add a number of semantic mappings depending on the domain of use.

So:

1) a mere require("nova-colors") would get the ASCII names (default export) 

2) a require("nova-colors").syntaxHighlighting would get syntax highlighting semantic names (type, variable, constant, current line, gutter, etc), 

3) a requite("nova-colors").versionControl would get semantic names for uses in git, mercurial, svn, etc.

**Comment by trevordmiller** [comment]
@bugpowder Thanks for the feedback! I agree. Feel free to submit a pull request [using the "CONTRIBUTING" guidelines](https://trevordmiller.github.io/nova); otherwise, I'll get to this :)

**Comment by trevordmiller** [comment]
Note: would be nice to also use these new non-default exports directly instead of mapping in each platform.

**Comment by trevordmiller** [comment]
Also note, I want to keep the default export as is as the majority of Nova instances are terminal based so having a 1:1 for ANSI names is helpful (nova-hyperterm, nova-git, nova-iterm, nova-tmux).

**Comment by Tyriar** [comment]
I would suggest something more like this:

```
{
  ansi: {
    ...
  }
  semantic: {
    // values derived from ansi above
    // this could also include source control concepts:
    //  add/positive, remove/negative, modified/neutral?
  }
}
```

If you're fine with the API breakage that is.

**Comment by trevordmiller** [comment]
@Tyriar Thanks for the feedback. I'm planning to keep the default export as is and add non-default exports for the color meanings (including source control status) to leverage the power of ES 2015 Modules (only import what you need instead of the entire object); this also has a side benefit of not breaking the API in use currently by 8 projects.

**Comment by Tyriar** [comment]
:+1:

**Comment by trevordmiller** [comment]
I've had a couple other people mention this and it is a good idea; I'd like to keep the ANSI default export but add other exports which map the colors to meanings depending on the context (syntax, git status, etc.).

cc: @iammerrick

**Comment by bugpowder** [comment]
> Feel free to submit a pull request using the "CONTRIBUTING" guidelines; otherwise, I'll get to this :)

Hello, nice to hear that the suggestion was liked. Catching up with the rest of the thread atm, if nobody else jumps to it, I'll try to have a go at that during the weekend.

**Comment by trevordmiller** [comment]
@bugpowder Sounds great :) Thanks.

**Comment by trevordmiller** [comment]
I merged a PR to resolve this issue; I ended up breaking API and bumping a major version but I think this will scale more nicely going forward - I implemented the feedback I received earlier. Thanks everyone. Feel free to take a look at the changes: https://github.com/trevordmiller/nova-colors/pull/24/files

**Comment by Tyriar** [comment]
Thanks @trevordmiller, I like it :smile:

**Comment by trevordmiller** [comment]
I've only updated one of the consuming plugins so far, but this is what the changes look like from a consumer perspective:
https://github.com/trevordmiller/nova-hyperterm/pull/12/files
