### ISSUE TITLE
Add IntelliJ plugin

### ISSUE THREAD

**Issue by LasseRafn** [trevordmiller/nova-colors#22]
I'd love me some Intellij plugins. PhpStorm would be so dope with this!

I'll likely work on a theme soon though. Will keep issue updated if so.

**Comment by trevordmiller** [comment]
I'm not planning on building/supporting this, but if someone else wants to, feel free - just follow the "CONTRIBUTING" guidelines on the website to use the `nova-colors` package for color values and follow the Nova color meanings :)

**Comment by trevordmiller** [comment]
@LasseRafn If you do create a plugin, let me know and I'll add it to the website. Feel free to host it in your own personal repos though as I don't plan to maintain an IntelliJ plugin :)

**Comment by LasseRafn** [comment]
@trevordmiller I totally respect that! :) 

Sure, well I'll go ahead and built something, following the guidelines. I really dig the color scheme

**Comment by trevordmiller** [comment]
Thanks!

**Comment by trevordmiller** [comment]
FYI @iammerrick

**Comment by iammerrick** [comment]
@LasseRafn Looking forward to what you come up with!

**Comment by davidsoderberg** [comment]
@LasseRafn have you made a theme yet?

**Comment by pjhartin** [comment]
@LasseRafn Would love to see an IntelliJ version. Would be happy to help if at all needed.

**Comment by trevordmiller** [comment]
@LasseRafn @pjhartin
@knittingcodemonkey was talking about making a PHP Storm version as well; I'm not as familiar with IntelliJ and all that, but it seems to me that maybe a Nova plugin could be built for IntelliJ that works for Webstorm / PHP Storm and the other offshoots of IntelliJ? Not sure. Either way, as mentioned before, if anyone creates a Nova theme that uses the `nova-colors` npm package correctly (see the "npm" tab of https://trevordmiller.com/projects/nova), I'll happily add it to the Nova website :)

**Comment by gabrielbidula** [comment]
Hi guys, any news for Add IntelliJ / PHPstorm theme?

**Comment by trevordmiller** [comment]
@gabrielbidula Thanks for the question! Nothing has changed since the last messages in this issue. The following is still the case:

> "I'm not planning on building/supporting this, but if someone else wants to, feel free - just follow the "CONTRIBUTING" guidelines on the website to use the nova-colors package for color values and follow the Nova color meaning...If you do create a plugin, let me know and I'll add it to the website. Feel free to host it in your own personal repos though as I don't plan to maintain an IntelliJ plugin"
