### ISSUE TITLE
Nova color theme for emacs

### ISSUE THREAD

**Issue by muirmanders** [trevordmiller/nova-colors#40]
Hi there

First, thanks for creating this color scheme. I really like it.

I have created an [emacs nova color theme](https://github.com/muirmanders/emacs-nova-theme). I'm hoping to get it listed on your nova site as a community plugin. Let me know if you want screenshots, information, etc.

Note that there is another emacs nova theme within the [emacs doom themes collection](https://github.com/hlissner/emacs-doom-themes), but I found it hard to work on since it is intertwined with the other doom themes.

**Comment by trevordmiller** [comment]
@muirmanders Awesome! Thanks so much for creating an emacs theme. I'll happily merge it in so it can be added to [the Nova website](https://trevordmiller.com/projects/nova) if you could submit a pull request to https://github.com/trevordmiller/trevordmiller-website with your plugin added [to the `communityPlugins` array](https://github.com/trevordmiller/trevordmiller-website/blob/master/pages/projects/nova/index.js#L220). Here is an example diff of another community plugin that was added: https://github.com/trevordmiller/trevordmiller-website/commit/81b940ff98350038394d697aa392d4ba210b4deb.

Please also add an emacs icon to [`components/Icon/utils/icons.js`](https://github.com/trevordmiller/trevordmiller-website/blob/master/components/Icon/utils/icons.js) to be used for the `icon` property.

Here is general contributing documentation for the website:
https://github.com/trevordmiller/trevordmiller-website/blob/master/contributing.md

Let me know if you have any questions or need any help. Thanks!

**Comment by trevordmiller** [comment]
@muirmanders I'm closing this for now since I haven't heard back from you but if you can do this please reopen :) Thanks!
