### ISSUE TITLE
Nova theme for Terminal.app in Mac OS

### ISSUE THREAD

**Issue by pesh1983** [trevordmiller/nova-colors#41]
Hi Trevor,

I very like your theme but I'm using standard Terminal.app as default terminal application in Mac OS. So I ported your iTerm settings to Terminal.app settings. It would be great if you add a link to my repo to your project's page so other people can find it as well. Here is the link https://github.com/pesh1983/nova-terminalapp. If you have any issues or comments, let me know, I will apply changes.

**Comment by trevordmiller** [comment]
@pesh1983 Hi there! Thanks for the support. I would love if this were possible, but unfortunately Mac Terminal.app doesn't support true color, so the colors you show are not actually correct. If Terminal.app ever gets true color support in the future, I'll gladly add it. Thank you.
